name: Deploy LactoControl Flutter Web

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.41.6'
        channel: stable


    - name: Flutter pub get
      run: flutter pub get


    - name: Build Flutter Web
      run: flutter build web --release


    # Remove old files
    - name: Clean old web files
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          rm -rf /var/www/lactocontrol_web/*


    # Upload directly to web root
    - name: Upload Flutter Web to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        source: "build/web/*"
        target: "/var/www/lactocontrol_web"
        strip_components: 2


    - name: Restart Nginx
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          nginx -t
          systemctl reload nginx